name: "Build and Deploy to Cloud Run"
on:
  push:
    branches:
      - "master"
    # paths:
    #   - 'backend/**'
env:
  PROJECT_ID: "ebvuevnievnuvni"
  REGION: "asia-east1"
  SERVICE: "stockify"
  WORKLOAD_IDENTITY_PROVIDER: "projects/525706028191/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
jobs:
  deploy:
    runs-on: "ubuntu-latest"
    environment: Production
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v3"
        with:
          project_id: "${{ env.PROJECT_ID }}"
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "525706028191-compute@developer.gserviceaccount.com"

      - id: "deploy"
        name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          service: "${{ env.SERVICE }}"
          region: "${{ env.REGION }}"
          source: "./backend"
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            PORT=${{ secrets.PORT }}
            GCS_PROJECT_ID=${{ secrets.GCS_PROJECT_ID }}
            GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }}
            ENVIRONMENT=${{ secrets.ENVIRONMENT }}

      - name: "Show output"
        run: echo ${{ steps.deploy.outputs.url }}
