name: 'Build and Deploy to Cloud Run'
on:
  push:
    branches:
      - 'master'
    paths:
      - 'backend/**'
env:
  PROJECT_ID: 'ebvuevnievnuvni'
  REGION: 'asia-east1'
  SERVICE: 'stockify'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/525706028191/locations/global/workloadIdentityPools/github-pool/github-provider'
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      - id: 'deploy'
        name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          source: './backend'   # path ke folder backend-mu

      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}
